INSERT INTO ingredientes (nombre) VALUES ('aceite de girasol');
INSERT INTO ingredientes (nombre) VALUES ('aceite de oliva');
INSERT INTO ingredientes (nombre) VALUES ('agua');
INSERT INTO ingredientes (nombre) VALUES ('ajo');
INSERT INTO ingredientes (nombre) VALUES ('alcachofa');
INSERT INTO ingredientes (nombre) VALUES ('alitas de pollo');
INSERT INTO ingredientes (nombre) VALUES ('almejas');
INSERT INTO ingredientes (nombre) VALUES ('anillas de calamar');
INSERT INTO ingredientes (nombre) VALUES ('apio');
INSERT INTO ingredientes (nombre) VALUES ('arenque');
INSERT INTO ingredientes (nombre) VALUES ('arroz');
INSERT INTO ingredientes (nombre) VALUES ('atun');
INSERT INTO ingredientes (nombre) VALUES ('avena');
INSERT INTO ingredientes (nombre) VALUES ('azucar');
INSERT INTO ingredientes (nombre) VALUES ('bacalao');
INSERT INTO ingredientes (nombre) VALUES ('bacalao desalado');
INSERT INTO ingredientes (nombre) VALUES ('bacon');
INSERT INTO ingredientes (nombre) VALUES ('berberechos');
INSERT INTO ingredientes (nombre) VALUES ('berenjena');
INSERT INTO ingredientes (nombre) VALUES ('boquerones');
INSERT INTO ingredientes (nombre) VALUES ('brocoli');
INSERT INTO ingredientes (nombre) VALUES ('butifarra');
INSERT INTO ingredientes (nombre) VALUES ('caballa');
INSERT INTO ingredientes (nombre) VALUES ('calabacin');
INSERT INTO ingredientes (nombre) VALUES ('calabaza');
INSERT INTO ingredientes (nombre) VALUES ('calamares');
INSERT INTO ingredientes (nombre) VALUES ('carne de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('carne de ternera');
INSERT INTO ingredientes (nombre) VALUES ('carne picada');
INSERT INTO ingredientes (nombre) VALUES ('cebolla');
INSERT INTO ingredientes (nombre) VALUES ('cebollino');
INSERT INTO ingredientes (nombre) VALUES ('cerdo');
INSERT INTO ingredientes (nombre) VALUES ('champiñon');
INSERT INTO ingredientes (nombre) VALUES ('chorizo');
INSERT INTO ingredientes (nombre) VALUES ('chuletas de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('chuleton de ternera');
INSERT INTO ingredientes (nombre) VALUES ('cilantro');
INSERT INTO ingredientes (nombre) VALUES ('codorniz');
INSERT INTO ingredientes (nombre) VALUES ('col');
INSERT INTO ingredientes (nombre) VALUES ('coliflor');
INSERT INTO ingredientes (nombre) VALUES ('comino');
INSERT INTO ingredientes (nombre) VALUES ('conejo');
INSERT INTO ingredientes (nombre) VALUES ('cordero');
INSERT INTO ingredientes (nombre) VALUES ('costillar de cordero');
INSERT INTO ingredientes (nombre) VALUES ('costillas de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('crema de leche');
INSERT INTO ingredientes (nombre) VALUES ('dorada');
INSERT INTO ingredientes (nombre) VALUES ('espaguetis');
INSERT INTO ingredientes (nombre) VALUES ('espinacas');
INSERT INTO ingredientes (nombre) VALUES ('esparragos');
INSERT INTO ingredientes (nombre) VALUES ('fresa');
INSERT INTO ingredientes (nombre) VALUES ('frijoles');
INSERT INTO ingredientes (nombre) VALUES ('gambas');
INSERT INTO ingredientes (nombre) VALUES ('garbanzos');
INSERT INTO ingredientes (nombre) VALUES ('guisantes');
INSERT INTO ingredientes (nombre) VALUES ('hamburguesa de pollo');
INSERT INTO ingredientes (nombre) VALUES ('hamburguesa de vacuno');
INSERT INTO ingredientes (nombre) VALUES ('huevo');
INSERT INTO ingredientes (nombre) VALUES ('huevos camperos');
INSERT INTO ingredientes (nombre) VALUES ('huevos de codorniz');
INSERT INTO ingredientes (nombre) VALUES ('huevos ecologicos');
INSERT INTO ingredientes (nombre) VALUES ('higado de pollo');
INSERT INTO ingredientes (nombre) VALUES ('higado de ternera');
INSERT INTO ingredientes (nombre) VALUES ('jamon');
INSERT INTO ingredientes (nombre) VALUES ('jamon iberico');
INSERT INTO ingredientes (nombre) VALUES ('jamon serrano');
INSERT INTO ingredientes (nombre) VALUES ('jamon york');
INSERT INTO ingredientes (nombre) VALUES ('judia verde');
INSERT INTO ingredientes (nombre) VALUES ('lacon');
INSERT INTO ingredientes (nombre) VALUES ('langostinos');
INSERT INTO ingredientes (nombre) VALUES ('leche de cabra');
INSERT INTO ingredientes (nombre) VALUES ('leche de vaca');
INSERT INTO ingredientes (nombre) VALUES ('leche desnatada');
INSERT INTO ingredientes (nombre) VALUES ('leche entera');
INSERT INTO ingredientes (nombre) VALUES ('lechuga');
INSERT INTO ingredientes (nombre) VALUES ('lentejas');
INSERT INTO ingredientes (nombre) VALUES ('limon');
INSERT INTO ingredientes (nombre) VALUES ('lomo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('longaniza');
INSERT INTO ingredientes (nombre) VALUES ('lubina');
INSERT INTO ingredientes (nombre) VALUES ('mantequilla');
INSERT INTO ingredientes (nombre) VALUES ('manzana');
INSERT INTO ingredientes (nombre) VALUES ('maiz');
INSERT INTO ingredientes (nombre) VALUES ('mejillones');
INSERT INTO ingredientes (nombre) VALUES ('melon');
INSERT INTO ingredientes (nombre) VALUES ('menta');
INSERT INTO ingredientes (nombre) VALUES ('merluza');
INSERT INTO ingredientes (nombre) VALUES ('merluza fresca');
INSERT INTO ingredientes (nombre) VALUES ('miel');
INSERT INTO ingredientes (nombre) VALUES ('morcilla');
INSERT INTO ingredientes (nombre) VALUES ('mostaza');
INSERT INTO ingredientes (nombre) VALUES ('muslo de pavo');
INSERT INTO ingredientes (nombre) VALUES ('muslo de pollo');
INSERT INTO ingredientes (nombre) VALUES ('naranja');
INSERT INTO ingredientes (nombre) VALUES ('nata');
INSERT INTO ingredientes (nombre) VALUES ('nata para cocinar');
INSERT INTO ingredientes (nombre) VALUES ('nata para montar');
INSERT INTO ingredientes (nombre) VALUES ('navajas');
INSERT INTO ingredientes (nombre) VALUES ('oregano');
INSERT INTO ingredientes (nombre) VALUES ('pan');
INSERT INTO ingredientes (nombre) VALUES ('patata');
INSERT INTO ingredientes (nombre) VALUES ('pato');
INSERT INTO ingredientes (nombre) VALUES ('pechuga de pollo');
INSERT INTO ingredientes (nombre) VALUES ('pepino');
INSERT INTO ingredientes (nombre) VALUES ('perejil');
INSERT INTO ingredientes (nombre) VALUES ('pez espada');
INSERT INTO ingredientes (nombre) VALUES ('pierna de cordero');
INSERT INTO ingredientes (nombre) VALUES ('pimiento rojo');
INSERT INTO ingredientes (nombre) VALUES ('pimiento verde');
INSERT INTO ingredientes (nombre) VALUES ('pollo');
INSERT INTO ingredientes (nombre) VALUES ('pulpo');
INSERT INTO ingredientes (nombre) VALUES ('queso');
INSERT INTO ingredientes (nombre) VALUES ('queso azul');
INSERT INTO ingredientes (nombre) VALUES ('queso brie');
INSERT INTO ingredientes (nombre) VALUES ('queso cheddar');
INSERT INTO ingredientes (nombre) VALUES ('queso de cabra');
INSERT INTO ingredientes (nombre) VALUES ('queso emmental');
INSERT INTO ingredientes (nombre) VALUES ('queso feta');
INSERT INTO ingredientes (nombre) VALUES ('queso gouda');
INSERT INTO ingredientes (nombre) VALUES ('queso manchego');
INSERT INTO ingredientes (nombre) VALUES ('queso mozzarella');
INSERT INTO ingredientes (nombre) VALUES ('queso parmesano');
INSERT INTO ingredientes (nombre) VALUES ('queso rallado');
INSERT INTO ingredientes (nombre) VALUES ('remolacha');
INSERT INTO ingredientes (nombre) VALUES ('romero');
INSERT INTO ingredientes (nombre) VALUES ('rabano');
INSERT INTO ingredientes (nombre) VALUES ('rucula');
INSERT INTO ingredientes (nombre) VALUES ('sal');
INSERT INTO ingredientes (nombre) VALUES ('salchichas');
INSERT INTO ingredientes (nombre) VALUES ('salchichas frescas');
INSERT INTO ingredientes (nombre) VALUES ('salchichón');
INSERT INTO ingredientes (nombre) VALUES ('salmon');
INSERT INTO ingredientes (nombre) VALUES ('sardinas');
INSERT INTO ingredientes (nombre) VALUES ('sepia');
INSERT INTO ingredientes (nombre) VALUES ('sobrasada');
INSERT INTO ingredientes (nombre) VALUES ('soja');
INSERT INTO ingredientes (nombre) VALUES ('solomillo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('solomillo de ternera');
INSERT INTO ingredientes (nombre) VALUES ('tomate');
INSERT INTO ingredientes (nombre) VALUES ('tomillo');
INSERT INTO ingredientes (nombre) VALUES ('trucha');
INSERT INTO ingredientes (nombre) VALUES ('uvas');
INSERT INTO ingredientes (nombre) VALUES ('vainilla');
INSERT INTO ingredientes (nombre) VALUES ('vinagre');
INSERT INTO ingredientes (nombre) VALUES ('yogur');
INSERT INTO ingredientes (nombre) VALUES ('yogur griego');
INSERT INTO ingredientes (nombre) VALUES ('yogur natural');
INSERT INTO ingredientes (nombre) VALUES ('zanahoria');